
n1 = str(input()).strip()
n2 = str(input()).strip()
n3 = str(input()).strip()
n4 = str(input()).strip()
n5 = str(input()).strip()
n6 = str(input()).strip()
n7 = str(input()).strip()
n8 = str(input()).strip()
n9 = str(input()).strip()
n10 = str(input()).strip()
print(n3)
print(n7)
print(n9)

